scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
         name: users-service
         instance: users-service
      - targets: ['host.docker.internal:8082']
        labels:
         name: couriers-service
         instance: couriers-service
      - targets: ['host.docker.internal:8083']
        labels:
         name: admin-service
         instance: admin-service
      - targets: ['host.docker.internal:8084']
        labels:
         name: orders-service
         instance: orders-service
      - targets: ['host.docker.internal:9500']
        labels:
         name: auth-server
         instance: auth-server
