version: '3.8'

services:
  postgresql:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresql://postgresql:5432/farel

    volumes:
      - ./scripts:/liquibase/scripts
      - ./scripts/liquibase/run-liquibase.sh:/liquibase/run-liquibase.sh
    command: /liquibase/run-liquibase.sh