server:
  port: 9500

logging:
  appender: stdout
  root:
    level: info
  gelf:
    url:
    port:

spring:
  application:
    name: auth server
  datasource:
    url: jdbc:postgresql://localhost:5432/farel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:9500
        introspection-endpoint: /oauth2/token-info
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect