server:
  port: 8081


spring:
  application:
    name: user service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9500
  datasource:
    url: jdbc:postgresql://localhost:5432/farel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    admin:
      auto-create: false

auth-server:
  url: http://localhost:9500/oauth2

retry:
  max-attempts: 3
  max-delay: 100

kafka:
  topics:
    order-create: t.order.create
    order-change-destination: t.order.change.destination
    order-cancel: t.order.cancel
