
-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: ./changelog/db.changelog-master.xml
-- Ran at: 1/30/24, 10:08 PM
-- Against: postgres@jdbc:postgresql://postgresql:5432/farel
-- Liquibase version: 4.25.1
-- *********************************************************************



CREATE TABLE public.roles (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, CONSTRAINT roles_pkey PRIMARY KEY (id));



CREATE TABLE public.persons (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, active BOOLEAN, mobile_number VARCHAR(255) NOT NULL, role_id INTEGER, CONSTRAINT persons_pkey PRIMARY KEY (id), CONSTRAINT fk_persons_roles FOREIGN KEY (role_id) REFERENCES public.roles(id));

CREATE TABLE public.admins (id INTEGER NOT NULL, superadmin BOOLEAN, CONSTRAINT admins_pkey PRIMARY KEY (id), CONSTRAINT fk_admins_persons FOREIGN KEY (id) REFERENCES public.persons(id));

CREATE TABLE public.users (id INTEGER NOT NULL, vip BOOLEAN, CONSTRAINT users_pkey PRIMARY KEY (id), CONSTRAINT fk_users_persons FOREIGN KEY (id) REFERENCES public.persons(id));

CREATE TABLE public.courier_statuses (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, CONSTRAINT courier_statuses_pkey PRIMARY KEY (id));

CREATE TABLE public.parcels (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INTEGER, item_name VARCHAR(255), CONSTRAINT parcels_pkey PRIMARY KEY (id), CONSTRAINT fk_parcels_users FOREIGN KEY (user_id) REFERENCES public.users(id));

CREATE TABLE public.couriers (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, courier_status_id INTEGER, CONSTRAINT couriers_pkey PRIMARY KEY (id), CONSTRAINT fk_couriers_persons FOREIGN KEY (id) REFERENCES public.persons(id), CONSTRAINT fk_couriers_courier_statuses FOREIGN KEY (courier_status_id) REFERENCES public.courier_statuses(id));

CREATE TABLE public.order_statuses (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, CONSTRAINT order_statuses_pkey PRIMARY KEY (id));

CREATE TABLE public.order_status_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, agent_id INTEGER, status_id INTEGER, change_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, CONSTRAINT order_status_history_pkey PRIMARY KEY (id), CONSTRAINT fk_history_order_statuses FOREIGN KEY (status_id) REFERENCES public.order_statuses(id), CONSTRAINT fk_history_persons FOREIGN KEY (agent_id) REFERENCES public.persons(id));

CREATE TABLE public.order_location (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_location POINT, finish_location POINT, current_location POINT, CONSTRAINT order_location_pkey PRIMARY KEY (id));

CREATE TABLE public.orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, parcel_id INTEGER, courier_id INTEGER, order_status_history_id INTEGER, order_location_id INTEGER, created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, start_time TIMESTAMP WITHOUT TIME ZONE, finish_time TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT orders_pkey PRIMARY KEY (id), CONSTRAINT fk_orders_parcels FOREIGN KEY (parcel_id) REFERENCES public.parcels(id), CONSTRAINT fk_orders_couriers FOREIGN KEY (courier_id) REFERENCES public.couriers(id), CONSTRAINT fk_orders_status_history FOREIGN KEY (order_status_history_id) REFERENCES public.order_status_history(id), CONSTRAINT fk_orders_locations FOREIGN KEY (order_location_id) REFERENCES public.order_location(id));

INSERT INTO public.roles (role) VALUES ('admin');

INSERT INTO public.roles (role) VALUES ('user');

INSERT INTO public.roles (role) VALUES ('courier');

-- Changeset changelog/v1.0.0/data.xml::insertPersonsData::radkevich

INSERT INTO public.persons (username, password, email, active, mobile_number, role_id) VALUES ('admin1', 'password', 'admin1@example.com', 'true', '1234567890', '1');

INSERT INTO public.persons (username, password, email, active, mobile_number, role_id) VALUES ('user1', 'password', 'user1@example.com', 'true', '9876543210', '2');

INSERT INTO public.persons (username, password, email, active, mobile_number, role_id) VALUES ('courier1', 'password', 'courier1@example.com', 'true', '5555555555', '3');

INSERT INTO public.persons (username, password, email, active, mobile_number, role_id) VALUES ('courier2', 'password', 'courier2@example.com', 'true', '52352', '3');

INSERT INTO public.persons (username, password, email, active, mobile_number, role_id) VALUES ('user2', 'password', 'user2@example.com', 'true', '9876543210', '2');

-- Changeset changelog/v1.0.0/data.xml::insertAdminsData::radkevich

INSERT INTO public.admins (id, superadmin) VALUES ('1', 'true');


-- Changeset changelog/v1.0.0/data.xml::insertUsersData::radkevich

INSERT INTO public.users (id, vip) VALUES ('2', 'false');
INSERT INTO public.users (id, vip) VALUES ('5', 'true');


-- Changeset changelog/v1.0.0/data.xml::insertCourierStatusesData::radkevich

INSERT INTO public.courier_statuses (status) VALUES ('Available');

INSERT INTO public.courier_statuses (status) VALUES ('In Transit');

INSERT INTO public.courier_statuses (status) VALUES ('Coffee Break');


-- Changeset changelog/v1.0.0/data.xml::insertCouriersData::radkevich

INSERT INTO public.couriers (id, courier_status_id) VALUES ('3', '2');

INSERT INTO public.couriers (id, courier_status_id) VALUES ('4', '2');


-- Changeset changelog/v1.0.0/data.xml::insertParcelsData::radkevich

INSERT INTO public.parcels (user_id, item_name) VALUES ('2', 'Electronics');

INSERT INTO public.parcels (user_id, item_name) VALUES ('2', 'Clothing');

INSERT INTO public.parcels (user_id, item_name) VALUES ('2', 'Food');
INSERT INTO public.parcels (user_id, item_name) VALUES ('5', 'Bomb');


-- Changeset changelog/v1.0.0/data.xml::insertOrderStatusesData::radkevich

INSERT INTO public.order_statuses (status) VALUES ('Created');

INSERT INTO public.order_statuses (status) VALUES ('Processing');

INSERT INTO public.order_statuses (status) VALUES ('In Transit');

INSERT INTO public.order_statuses (status) VALUES ('Delivered');

INSERT INTO public.order_statuses (status) VALUES ('Cancelled');


-- Changeset changelog/v1.0.0/data.xml::insertOrderLocationData::radkevich

INSERT INTO public.order_location (start_location, finish_location, current_location) VALUES ('40.7128, -74.0060', '41.8781, -87.6298', '40.7128, -74.0060');

INSERT INTO public.order_location (start_location, finish_location, current_location) VALUES ('34.0522, -118.2437', NULL, NULL);

INSERT INTO public.order_location (start_location, finish_location, current_location) VALUES ('1, -12', '34.0522, -118.2437', '32, -114');


-- Changeset changelog/v1.0.0/data.xml::insertOrderStatusHistoryData::radkevich

INSERT INTO public.order_status_history (agent_id, status_id, change_time) VALUES ('1', '1', '2024-01-29 12:30:00');

INSERT INTO public.order_status_history (agent_id, status_id, change_time) VALUES ('3', '2', '2024-01-29 14:00:00');

INSERT INTO public.order_status_history (agent_id, status_id, change_time) VALUES ('1', '3', '2024-01-29 15:00:00');


-- Changeset changelog/v1.0.0/data.xml::insertOrdersData::radkevich

INSERT INTO public.orders (parcel_id, courier_id, order_status_history_id, order_location_id, created_time, start_time, finish_time) VALUES ('1', '3', '1', '1', '2024-01-29 12:00:00', NULL, NULL);

INSERT INTO public.orders (parcel_id, courier_id, order_status_history_id, order_location_id, created_time, start_time, finish_time) VALUES ('2', '4', '2', '2', '2024-01-29 13:30:00', NULL, NULL);

INSERT INTO public.orders (parcel_id, courier_id, order_status_history_id, order_location_id, created_time, start_time, finish_time) VALUES ('3', '4', '3', '3', '2024-01-29 14:30:00', '2024-01-29 14:31:00', '2024-01-29 14:35:00');
INSERT INTO public.orders (parcel_id, courier_id, order_status_history_id, order_location_id, created_time, start_time, finish_time) VALUES ('3', '4', '3', '3', '2024-01-29 14:30:00', '2024-01-29 14:31:00', '2024-01-29 14:35:00');


