server:
  port: ${SERVER_PORT}

logging:
  appender: ${LOGGING_APPENDER}
  root:
    level: info
  gelf:
    url: ${LOGGING_APPENDER_URL}
    port: ${LOGGING_APPENDER_PORT}


spring:
  application:
    name: couriers service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URL}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTH_DATABASE}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

auth-server:
  url: ${JWT_ISSUER_URL}/oauth2

retry:
  max-attempts: 3
  max-delay: 100


kafka:
  topics:
    order-change-status: ${TOPIC_CHANGE_STATUS}
    order-assign-courier: ${TOPIC_ASSIGN_COURIER}
    order-create-courier: ${TOPIC_CREATE_COURIER}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
